version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - dev-db-data:/app/data
    environment:
      - PYTHONPATH=/app/src
      - DATABASE_URL=sqlite:///data/dev.db
      - SECRET_KEY=dev_secret_key
      - ACCESS_TOKEN_EXPIRES_MINUTES=60
      - DEBUG=True
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  dev-db-data: