name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurando Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Instalando Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Iniciando Docker Compose
        run: |
          docker-compose -f docker-compose-test.yml up -d --build
          docker ps

      - name: Aguardando aplicação iniciar
        run: |
          timeout=60
          counter=0
          until curl -s http://localhost:8000/docs > /dev/null; do
            if [ $counter -eq $timeout ]; then
              echo "Aplicação não iniciou em $timeout segundos"
              exit 1
            fi
            echo "Aguardando aplicação iniciar..."
            sleep 1
            counter=$((counter + 1))
          done

      - name: Instalar dependências do teste
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          pip install -r requirements.txt

      - name: Executando Testes de Integração
        run: |
          echo "Criando usuário teste"
          REGISTER_RESPONSE=$(curl -s -X POST "http://localhost:8000/auth/register" \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"testuser\",\"password\":\"testpass123\"}")
          echo "Resposta do registro: $REGISTER_RESPONSE"

          echo "Gerando token de acesso"
          TOKEN_RESPONSE=$(curl -s -X POST "http://localhost:8000/auth/token" \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"testuser\",\"password\":\"testpass123\"}")
          TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          echo "Token obtido com sucesso!"

          echo "Criando sala de reunião"
          ROOM_RESPONSE=$(curl -s -X POST "http://localhost:8000/rooms/" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"Sala Teste\",\"capacity\":10,\"location\":\"Andar 1\"}")
          ROOM_ID=$(echo "$ROOM_RESPONSE" | jq -r '.id')
          echo "Sala criada com ID: $ROOM_ID"

          echo "Criando reserva"
          RESERVATION_RESPONSE=$(curl -s -X POST "http://localhost:8000/reservations/" \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"room_id\":\"$ROOM_ID\",\"start_time\":\"2025-02-10T14:00:00\",\"end_time\":\"2025-02-10T15:00:00\"}")
          echo "Resposta da criação da reserva: $RESERVATION_RESPONSE"

          echo "Checando disponibilidade"
          AVAILABILITY_RESPONSE=$(curl -s -X GET "http://localhost:8000/rooms/$ROOM_ID/availability?start_time=2025-02-10T16:00:00&end_time=2025-02-10T17:00:00")
          echo "Resposta da disponibilidade: $AVAILABILITY_RESPONSE"

          echo "Listando reservas"
          RESERVATIONS_RESPONSE=$(curl -s -X GET "http://localhost:8000/rooms/$ROOM_ID/reservations")
          echo "Resposta da lista de reservas: $RESERVATIONS_RESPONSE"

      - name: Checando logs
        if: always()
        run: |
          echo "Docker Compose Logs:"
          docker-compose logs

      - name: Limpando ambiente
        if: always()
        run: |
          docker-compose down -v
          docker system prune -af